# Generated by Django 4.0.10 on 2023-06-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
