# Generated by Django 4.0.10 on 2023-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0002_userapplication_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='about_me_translated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
